/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'keyHash', 'lastUsedAt', 'name', 'revokedAt'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyHash: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare revokedAt: DateTime | null
}

export class BookmarkSchema extends BaseModel {
  static $columns = [
    'description',
    'embedData',
    'embedding',
    'embeddingSourceText',
    'enrichedAt',
    'enrichmentAttempts',
    'enrichmentError',
    'enrichmentFailureReason',
    'enrichmentStatus',
    'id',
    'lastSavedAt',
    'ogImage',
    'savedAt',
    'savedCount',
    'savedFrom',
    'tags',
    'title',
    'type',
    'url',
    'urlHash',
  ] as const
  $columns = BookmarkSchema.$columns
  @column()
  declare description: string
  @column()
  declare embedData: any | null
  @column()
  declare embedding: any | null
  @column()
  declare embeddingSourceText: string | null
  @column.dateTime()
  declare enrichedAt: DateTime | null
  @column()
  declare enrichmentAttempts: number
  @column()
  declare enrichmentError: string | null
  @column()
  declare enrichmentFailureReason: string | null
  @column()
  declare enrichmentStatus: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastSavedAt: DateTime
  @column()
  declare ogImage: string | null
  @column.dateTime()
  declare savedAt: DateTime
  @column()
  declare savedCount: number
  @column()
  declare savedFrom: any
  @column()
  declare tags: any
  @column()
  declare title: string
  @column()
  declare type: string
  @column()
  declare url: string
  @column()
  declare urlHash: string
}
