/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'keyHash', 'lastUsedAt', 'name', 'revokedAt'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare keyHash: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare revokedAt: DateTime | null
}

export class BookmarkSchema extends BaseModel {
  static $columns = [
    'captureByteSize',
    'captureHeight',
    'captureMimeType',
    'capturePath',
    'captureSource',
    'captureUrl',
    'captureWidth',
    'capturedAt',
    'description',
    'embedData',
    'embedding',
    'embeddingSourceText',
    'enrichedAt',
    'enrichmentAttempts',
    'enrichmentError',
    'enrichmentFailureReason',
    'enrichmentStatus',
    'id',
    'isMedia',
    'lastSavedAt',
    'mediaKind',
    'mediaProvider',
    'ogImage',
    'savedAt',
    'savedCount',
    'savedFrom',
    'tags',
    'title',
    'transcribedAt',
    'transcriptionError',
    'transcriptionStatus',
    'transcriptionText',
    'type',
    'url',
    'urlHash',
  ] as const
  $columns = BookmarkSchema.$columns
  @column()
  declare captureByteSize: number | null
  @column()
  declare captureHeight: number | null
  @column()
  declare captureMimeType: string | null
  @column()
  declare capturePath: string | null
  @column()
  declare captureSource: string | null
  @column()
  declare captureUrl: string | null
  @column()
  declare captureWidth: number | null
  @column.dateTime()
  declare capturedAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare embedData: any | null
  @column()
  declare embedding: any | null
  @column()
  declare embeddingSourceText: string | null
  @column.dateTime()
  declare enrichedAt: DateTime | null
  @column()
  declare enrichmentAttempts: number
  @column()
  declare enrichmentError: string | null
  @column()
  declare enrichmentFailureReason: string | null
  @column()
  declare enrichmentStatus: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isMedia: boolean
  @column.dateTime()
  declare lastSavedAt: DateTime
  @column()
  declare mediaKind: string | null
  @column()
  declare mediaProvider: string | null
  @column()
  declare ogImage: string | null
  @column.dateTime()
  declare savedAt: DateTime
  @column()
  declare savedCount: number
  @column()
  declare savedFrom: any
  @column()
  declare tags: any
  @column()
  declare title: string
  @column.dateTime()
  declare transcribedAt: DateTime | null
  @column()
  declare transcriptionError: string | null
  @column()
  declare transcriptionStatus: string
  @column()
  declare transcriptionText: string | null
  @column()
  declare type: string
  @column()
  declare url: string
  @column()
  declare urlHash: string
}

export class SiteCredentialSchema extends BaseModel {
  static $columns = [
    'cookieCount',
    'createdAt',
    'domain',
    'encryptedCookies',
    'id',
    'updatedAt',
  ] as const
  $columns = SiteCredentialSchema.$columns
  @column()
  declare cookieCount: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: string
  @column()
  declare encryptedCookies: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
